version: '3.3'
services:
    alice:
        image: nginx
        ports:
            - "10443:443"
        volumes:
            - ./nginx/alice.html:/usr/share/nginx/html/index.html
            - ./nginx/alice.conf:/etc/nginx/conf.d/default.conf
            - ../temp/alice/alice.crt:/etc/ssl/certs/nginx/alice.crt
            - ../temp/alice/alice.key:/etc/ssl/certs/nginx/alice.key
